# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('formulation', models.CharField(max_length=30)),
                ('sub_category', models.CharField(max_length=100)),
            ],
        ),
    ]
