# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='image',
            field=models.FileField(upload_to='medi'),
        ),
    ]
