# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0002_auto_20160916_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('ccount', models.IntegerField()),
            ],
        ),
    ]
