# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='med_id',
        ),
        migrations.AddField(
            model_name='order',
            name='medid',
            field=models.IntegerField(default=98),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='User_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
