# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0006_auto_20160919_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='medid',
            new_name='med_id',
        ),
    ]
