# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0007_auto_20160919_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
