# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0008_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(max_length=250)),
                ('tab_price', models.FloatField()),
                ('tab_manufacturer', models.CharField(max_length=250)),
                ('tab_sideeff', models.CharField(max_length=250)),
            ],
        ),
    ]
