# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 13:39
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0010_ordertab'),
    ]

    operations = [
        migrations.CreateModel(
            name='hii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('je', models.IntegerField()),
                ('hf', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tablets',
            name='tab_or',
            field=models.CharField(max_length=200, null=builtins.any),
        ),
    ]
