# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0011_auto_20160921_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hii',
        ),
        migrations.RemoveField(
            model_name='tablets',
            name='tab_or',
        ),
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
