# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0013_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertab',
            name='flagt',
            field=models.IntegerField(default=1),
        ),
    ]
