# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0014_ordertab_flagt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flago',
            field=models.IntegerField(default=1),
        ),
    ]
