# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0016_test_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertab',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
