# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0019_auto_20160925_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertab',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
