# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promeds', '0021_ordertab_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='billmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='billmed',
            name='ordermed',
            field=models.ManyToManyField(to='promeds.order'),
        ),
        migrations.AddField(
            model_name='billmed',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
