# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0024_billmed_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='totalprice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
