# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0025_bill_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertab',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
