# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0026_auto_20160928_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='billmed',
            name='billdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='billmed',
            name='totalprice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordertab',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
