# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0027_auto_20160928_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billdate',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='billmed',
            name='billdate',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='ordertab',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
