# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 09:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promeds', '0029_auto_20160929_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(max_length=250)),
                ('date_app1', models.DateField(default=datetime.datetime.utcnow)),
                ('time_slot', models.CharField(default=1, max_length=250)),
                ('Date_of_booking', models.DateField(default=datetime.datetime.utcnow)),
                ('flag_app', models.IntegerField(default=1)),
                ('User_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='checktest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storetest', models.CharField(max_length=250)),
                ('flagtest', models.IntegerField(default=1)),
                ('test_id', models.IntegerField(default=1)),
                ('User_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='selected',
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.CharField(default='15mins', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
