# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0031_billtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billtest',
            name='ordertest',
        ),
        migrations.RemoveField(
            model_name='billtest',
            name='users',
        ),
        migrations.AddField(
            model_name='appointment',
            name='ordertest',
            field=models.ManyToManyField(to='promeds.checktest'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='totalprice',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='billtest',
        ),
    ]
