# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0032_auto_20161002_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date_of_booking',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
