# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0033_auto_20161003_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date_of_booking',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
