# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promeds', '0036_usershippingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershippingdetails',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='landmark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usershippingdetails',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
